---
title: International Autumn School on AI and Robotics for Sustainable Agricultural Systems (SAIRSAS 2023)  
description: Web of International Autumn School on AI and Robotics for Sustainable Agricultural Systems (SAIRSAS 2023)  
---
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
