---
title: International Autumn School on AI and Robotics for Sustainable Agricultural Systems (SAIRSAS 2023)  
description: Web of International Autumn School on AI and Robotics for Sustainable Agricultural Systems (SAIRSAS 2023)  
---
theme: jekyll-theme-cayman
