url: https://shepherd-robot.github.io
baseurl: /sairsas.github.io/

# Site settings
title: SAIRSAS 2023
email: lidia.sanchez@unileon.es
description: "Web of the International Autumn School on AI and Robotics for Sustainable Agricultural Systems (SAIRSAS 2023)"


# Team names, titles and social links
people:
- name: Francisco J. Rodríguez Lera
  pic: 1
  position: Organizer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Lidia Sánchez González
  pic: 2
  position: Organizer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: https://es.linkedin.com/in/lidia-s%C3%A1nchez-gonz%C3%A1lez-773b65213

- name: Vicente Matellán
  pic: 3
  position: Organizer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/RoboticaUnileon
  - title: instagram
    url: https://www.instagram.com/roboticaunileon/
  - title: linkedin
    url: https://es.linkedin.com/company/grupo-robotica-unileon
  - title: google-plus 
    url: https://robotica.unileon.es/projects/shephered_robot/
  - title: github
    url: https://github.com/uleroboticsgroup

# Postal address (add as many lines as necessary)
address:
  - line: Grupo de Robótica
  - line: Universidad de León

# Build settings
markdown: kramdown
permalink: pretty
